### ISSUE TITLE
Redesign configuration UI and add "weapon drawn" state

### ISSUE THREAD

**Issue by shdwp** [shdwp/xivFaderPlugin#17]
Currently there are too much states to add another, but with proper UI there might be room for new stuff.

**Comment by Iaotle** [comment]
what kind of redesign do you suggest?

**Comment by shdwp** [comment]
Configuration UI. There are way too many elements in that matrix, its very hard to navigate as is.

**Comment by gucciBane** [comment]
Would love to see weapon drawn as well!

**Comment by LastExceed** [comment]
basically the general issue is that too much information is displayed at once, which can be overwhelming. here are 2 ideas how to address this:
* instead of showing all "states" (idle/duty/hasEnemyTarget/etc) at the same time, create a dropdown where you can select the state you want to configure. that way only 1 state is visible at a time, which would shrink the config UI by about 90%
* instead of listing all possible elements with 1 button for each, create a "show" list and a "hide" list where you can add the individual UI elements. that way only the elements that change their visibility in the given state are on screen, and "skipped" elements are not. keeping both lists empty would be the equivalent of setting an entire column in the current UI to "skip"

**Comment by Iaotle** [comment]
I actually disagree. Keeping track of what states have which bar enabled without being able to see them all in one place would be a nightmare. The spreadsheet layout with highlights is the best I can think of.

**Comment by Mixxy92** [comment]
I think the layout is fine but I would also second the request for a weapon drawn state, if its possible

**Comment by Rellawing** [comment]
I would love to see weapon drawn state added. It's a bit more polished than combat state, although I'd want to keep that. Basically I'd put drawn weapon over most every state and combat after so it will trigger (or the reverse?) in fights.

**Comment by Infiziert90** [comment]
Weapon drawn and small improvements to UI got added with the latest updates, so gonna close this as complete
