### ISSUE TITLE
crossbar is showing on top left when hidden in ultra wide screen

### ISSUE THREAD

**Issue by jasonh1024** [shdwp/xivFaderPlugin#54]
crossbar is showing on top left when hidden in ultra wide screen

**Comment by siklr** [comment]
Could you provide your resolution? UI elements are moved "offscreen" to prevent interaction.

**Comment by justcallmediggy** [comment]
I'm having the same problem with the cross hotbar in 1920x1080. It shows the top right hotbar of my WXHB hotbars.

**Comment by justcallmediggy** [comment]
Actually I just realized it shows both of my top hotbars in the top left corner, they just overlap each other

**Comment by Shanespeed** [comment]
Same issue, ever since the last update months ago. 2560x1440 is my resolution. Crossbar is partially shown in the top left corner.

**Comment by siklr** [comment]
Could you confirm if this is only the WXHB? Just tried with the regular XHB and wasn't able to replicate with a 2560x1440 display. However, I did notice that if always display WXHB is enabled and the XHB is set to be hidden, the WXHB is displayed in the upper right corner.

**Comment by jasonh1024** [comment]
apologies just saw the update. yeah it's just with the WXHB, always display. My resolution is 3840*1200

**Comment by Infiziert90** [comment]
The issue here is how WXHB works.

There default position is always fixed to be above the XHB, but the game forces this position to be inside of the players resolution, so the moment XHB gets moved to -9999 -9999 fails this game check and it is forced into 0 0.
The only way to prevent this is by activating "Position WXHB separately from XHB", with this option active the WXHB will be placed outside the screen just like XHB.

**Comment by jasonh1024** [comment]
separation setting works. huge thanks.
